TOP_PLAYERS = [
{"id":1,"name":"Gabrielle Reece","age":45,"birthplace":"La Jolla, San Diego, California, United States of America"},
{"id":2,"name":"Kerri Walsh Jennings","age":37,"birthplace":"Santa Clara, California, United States of America"},
{"id":3,"name":"Francesca Piccini","age":36,"birthplace":"Massa, Italy"},
{"id":4,"name":"Jaqueline Carvalho","age":32,"birthplace":"Recife, Brazil"},
{"id":5,"name":"April Ross","age":33,"birthplace":"Costa Mesa, California, United States of America"},
{"id":6,"name":"Destinee Hooker","age":28,"birthplace":"Frankfurt (Oder), Germany"},
{"id":7,"name":"Prisilla Rivera","age":31,"birthplace":"Santo Domingo, Dominican Republic"},
{"id":8,"name":"Dallal Merwa Achour","age":21,"birthplace":"Blida, Algeria"},
{"id":9,"name":"Fernanda Garay","age":29,"birthplace":"Porto Alegre, Brazil"},
{"id":10,"name":"Antonella Del Core","age":35,"birthplace":"Naples, Italy"},
{"id":11,"name":"Misty May-Treanor","age":38,"birthplace":"Los Angeles, California, United States of America"},
{"id":12,"name":"Sara Goller","age":31,"birthplace":"Starnberg, Germany"},
{"id":13,"name":"Maria Borodakova","age":29,"birthplace":"Nizhny Novgorod, Russia"},
{"id":14,"name":"Stacy Sykora","age":38,"birthplace":"Fort Worth, Texas, United States of America"},
{"id":15,"name":"Ciara Michel","age":30,"birthplace":"Taunton, Massachusetts, United States of America"},
{"id":16,"name":"Elizabeth Reid","age":26,"birthplace":"London, United Kingdom"},
{"id":17,"name":"Nellie Spicer","age":28,"birthplace":"Barrington, Illinois, United States of America"},
{"id":18,"name":"Neslihan Demir","age":32,"birthplace":"Eskişehir, Turkey"},
{"id":19,"name":"Kaori Inoue","age":33,"birthplace":"Toyooka, Japan"},
{"id":20,"name":"Saori Sakoda","age":28,"birthplace":"Kagoshima, Japan"}];
